config/routes.rb
Sko::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

  get "learnings/memo" => "learnings#memo"
  resources "learnings"

  resources "friends"

  resources "messages", :except => [:index, :show]

  get "faq/index"

  get 'contact/new' => 'contact#new', :as => 'contact'
  post 'contact/new' => 'contact#create'
  get 'contact:notice' => 'contact#index'

  get "lessons/new_lesson"
  get "lessons/ranking"
  get "lessons/category"
  get "lessons", :to => 'lessons#index', :as => 'lessons'

  get "grade3/index" => 'lessons#grade'
  get "grade2/index" => 'lessons#grade'
  get "grade1/index" => 'lessons#grade'
  match 'grade1/:type' => 'lessons#tangen', via: :get
  match 'grade1/:type/:lesson' => 'lessons#show', via: :get
  match 'grade2/:type' => 'lessons#tangen', via: :get
  match 'grade2/:type/:lesson' => 'lessons#show', via: :get
  match 'grade3/:type' => 'lessons#tangen', via: :get
  match 'grade3/:type/:lesson' => 'lessons#show', via: :get

  get 'agreement' => 'lessons#agreement'
  get 'privacy' => 'lessons#privacy'

  root :to => 'lessons#home'

end

app/models/learning.rb
class Learning < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson, :order => 'grade'
  # attr_accessible :check, :complete_date, :memo, :status
end

app/controllers/learnings_controller.rb
# coding utf-8

class LearningsController < ApplicationController
  add_breadcrumb 'Home', '/'

  protect_from_forgery

  before_filter :set_search
  before_filter :authenticate_user!

  def set_search
  @search = Lesson.search(params[:q])
  end

  def index

    add_breadcrumb 'マイページ'

    @title = '学習状況マイページ'
    @description = '個人の学習状況を確認するページです。'

    @user_id = current_user.id

    @chart_data_day = Learning.where("user_id = ? and status = ?", @user_id, true).group('date(complete_date)').count
    @columun = 0
    @accumulation = 0
    @chart_data_accumulation = @chart_data_day.to_a
    @chart_data_day.each do |day|
      @chart_data_accumulation[@columun][0] = day[0]
      @chart_data_accumulation[@columun][1] = day[1] + @accumulation
      @accumulation = @chart_data_accumulation[@columun][1]
      @columun += 1
    end

    # Newの表示
    @time_now = Time.now.to_i
    # Newの表示日
    dif_day = 3
    @new_period = 60 * 60 * 24 * dif_day

    @from_friend_times = Friend.where(:to => @user_id, :status => false).pluck(:updated_at)

    @new_disp = false
    @from_friend_times.each do |t|
      if @time_now - t.to_i < @new_period
        @new_disp = true
      end
    end

    @learning_ids = Learning.where("user_id = ? and status = ?", @user_id, true).group('lesson_id').count('lesson_id').keys

    @lessons1 = Lesson.where(:grade => '1').select('grade, unit_name, unit_item_name').group('unit_item_name')
    @lessons2 = Lesson.where(:grade => '2').select('grade, unit_name, unit_item_name').group('unit_item_name')
    @lessons3 = Lesson.where(:grade => '3').select('grade, unit_name, unit_item_name').group('unit_item_name')

    @l_unit_names1 = Lesson.where(:grade => '1', :id => @learning_ids).group('unit_item_name').count
    @unit_count1 = Lesson.where(:grade => '1').group('unit_item_name').count
    @l_unit_names2 = Lesson.where(:grade => '2', :id => @learning_ids).group('unit_item_name').count
    @unit_count2 = Lesson.where(:grade => '2').group('unit_item_name').count
    @l_unit_names3 = Lesson.where(:grade => '3', :id => @learning_ids).group('unit_item_name').count
    @unit_count3 = Lesson.where(:grade => '3').group('unit_item_name').count

    @sum_time = 0
    @times = Lesson.where(:id => @learning_ids).select('time')

    if @times.present?
      @times.each do |t|
        @sum_time += t.time.min * 60 + t.time.sec
      end
    end

    @total_time = Time.now.midnight.advance(:seconds => @sum_time).strftime('%T')

  end

  def memo

    add_breadcrumb '学習メモ・チェックレッスン'

    @title = '学習メモ・チェックレッスン'
    @description = '各レッスンでのメモやチェックしたレッスン一覧を表示します。'

    @user_id = current_user.id

    @memos = Learning.where("user_id = ?", @user_id).select('lesson_id, memo')

    @checks = Learning.where(:user_id => @user_id, :check => true).select('lesson_id')

    # Newの表示
    @time_now = Time.now.to_i
    # Newの表示日
    dif_day = 3
    @new_period = 60 * 60 * 24 * dif_day

    @from_friend_times = Friend.where(:to => @user_id, :status => false).pluck(:updated_at)

    @new_disp = false
    @from_friend_times.each do |t|
      if @time_now - t.to_i < @new_period
        @new_disp = true
      end
    end

  end

  def create
    @learning = Learning.new(learning_params)
    if @learning.save
      status = 'success'
      # redirect_to :back
    else
      status = 'error'
      # render :template => "params[:controller]/params[:action]", :locals => {:learning => @learning}
    end
    render json: { status: status, data: @learning }
  end

  def update
    @learning = Learning.find(params[:id])
    if params[:learning][:check].present?
      check = params[:learning][:check]
    end
    if params[:learning][:status].present?
      complete = params[:learning][:status]
      if complete == 'true'
        params[:learning][:complete_date] = Time.now
      end
    end

    if @learning.update(learning_params)
      status_s = 'success'
    else
      status_s = 'error'
    end
    @learning = Learning.find_by_id(params[:id])

    if check.present?
      render 'learnings/check'
    elsif complete.present?
      render 'learnings/complete'
    end
  end

  def check_lesson_info

  end

  private

      def learning_params
          params[:learning].permit(:user_id, :lesson_id, :status, :memo, :check, :complete_date)
      end

 end

app/helpers/learnings_helper.rb
module LearningsHelper
end

app/views/learnings/_check_lesson.html.erb
              <% if user_signed_in? %>
                <div id="check" class="col-xs-2">
                  <% if @learning.present? && @learning.check == true %>
                    <%= form_for @learning, remote: true do |f| %>
                      <%= f.hidden_field :check, :value => 'false' %>
                      <%= f.submit 'チェック済み', :class => "btn btn-warning btn-sm lesson_check", :style => 'width: 90px;' %>
                    <% end %>
                  <% else %>
                    <%= form_for @learning, remote: true do |f| %>
                      <%= f.hidden_field :check, :value => 'true' %>
                      <%= f.submit 'チェックする', :class => "btn btn-info btn-sm lesson_check", :style => 'width: 90px;' %>
                    <% end %>
                  <% end %>
                </div>
              <% end %>

app/views/learnings/_complete_lesson.html.erb
                <% if user_signed_in? %>
                  <% if @learning.present? && @learning.status == true %>
                    <%= form_for @learning, remote: true do |f| %>
                      <%= f.hidden_field :status, :value => 'false' %>
                      <%= f.submit '完了済み', :class => "btn btn-success", :style => 'width: 80px;' %>
                    <% end %>
                  <% else %>
                    <%= form_for @learning, remote: true do |f| %>
                      <%= f.hidden_field :status, :value => 'true' %>
                      <%= f.submit '完了', :class => "btn btn-default", :style => 'width: 80px;' %>
                    <% end %>
                  <% end %>
                <% end %>

app/views/learnings/check.js.erb
$('#check_lesson_info').html(
  "<%= escape_javascript(render 'learnings/check_lesson', :learning => @learning) %>"
);

app/views/learnings/complete.js.erb
$('#complete_lesson_info').html(
  "<%= escape_javascript(render 'learnings/complete_lesson', :learning => @learning) %>"
);

app/views/learnings/index.html.erb
            <ul class="nav nav-tabs">
              <li class="active"><a>学習状況</a></li>
              <li><a href="<%= learnings_memo_path %>"><span style="font-size: 12px; line-height: 120%; !important">メモ・チェックレッスン</a></li>
              <li><a href="<%= friends_path %>">友達
                <% if @new_disp == true %>
                  <span style="color: red; font-size: 12px">New</span>
                <% end %>
              </a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active" id="progress">
                <% if @chart_data_day.count > 0 %>
                  <div  style="border: 1px solid #ccc; margin-top: 7px;">
                    <div class="tab-content">
                      <div class="tab-pane active" id="days">
                        <h3>日別学習レッスン数</h3>
                        <%= line_chart @chart_data_day, height: "300px" %>
                      </div>
                      <div class="tab-pane" id="total">
                        <h3>累積学習レッスン数</h3>
                        <%= line_chart @chart_data_accumulation, height: "300px" %>
                      </div>
                    </div>
                    <ul class="nav nav-pills nav-justified">
                      <li class="active"><a href="#days" data-toggle="tab">日別学習時間</a></li>
                      <li><a href="#total" data-toggle="tab">累積学習時間</a></li>
                    </ul>
                  </div>
                <% end %>

                      <% comp = "" %>
                      <% incomp = "" %>

                      <% @l_unit_names1.each do |l| %>
                        <% @unit_count1.each do |c| %>
                          <% if c[0] == l[0] %>
                            <% if c[1] <= l[1] %>
                              <% @lessons1.each do |ls| %>
                                <% if ls.unit_item_name == l[0] %>
                                  <% comp += "<li><a href='/grade#{ls.grade}/#{l[0]}'>【中学#{ls.grade}年生】#{ls.unit_name}：#{l[0]}</a></li>" %>
                                <% end %>
                              <% end %>
                            <% else %>
                              <% @lessons1.each do |ls| %>
                                <% if ls.unit_item_name == l[0] %>
                                  <% incomp += "<li><a href='/grade#{ls.grade}/#{l[0]}'>【中学#{ls.grade}年生】#{ls.unit_name}：#{l[0]}</a></li>" %>
                                <% end %>
                              <% end %>
                            <% end %>
                          <% end %>
                        <% end %>
                      <% end %>
                      <% @l_unit_names2.each do |l| %>
                        <% @unit_count2.each do |c| %>
                          <% if c[0] == l[0] %>
                            <% if c[1] <= l[1] %>
                              <% @lessons2.each do |ls| %>
                                <% if ls.unit_item_name == l[0] %>
                                  <% comp += "<li><a href='/grade#{ls.grade}/#{l[0]}'>【中学#{ls.grade}年生】#{ls.unit_name}：#{l[0]}</a></li>" %>
                                <% end %>
                              <% end %>
                            <% else %>
                              <% @lessons2.each do |ls| %>
                                <% if ls.unit_item_name == l[0] %>
                                  <% incomp += "<li><a href='/grade#{ls.grade}/#{l[0]}'>【中学#{ls.grade}年生】#{ls.unit_name}：#{l[0]}</a></li>" %>
                                <% end %>
                              <% end %>
                            <% end %>
                          <% end %>
                        <% end %>
                      <% end %>
                      <% @l_unit_names3.each do |l| %>
                        <% @unit_count3.each do |c| %>
                          <% if c[0] == l[0] %>
                            <% if c[1] <= l[1] %>
                              <% @lessons3.each do |ls| %>
                                <% if ls.unit_item_name == l[0] %>
                                  <% comp += "<li><a href='/grade#{ls.grade}/#{l[0]}'>【中学#{ls.grade}年生】#{ls.unit_name}：#{l[0]}</a></li>" %>
                                <% end %>
                              <% end %>
                            <% else %>
                              <% @lessons3.each do |ls| %>
                                <% if ls.unit_item_name == l[0] %>
                                  <% incomp += "<li><a href='/grade#{ls.grade}/#{l[0]}'>【中学#{ls.grade}年生】#{ls.unit_name}：#{l[0]}</a></li>" %>
                                <% end %>
                              <% end %>
                            <% end %>
                          <% end %>
                        <% end %>
                      <% end %>

                <div class="col-xs-12">
                  <h3 class="tangen">学習中レッスン一覧</h3>
                  <ul>
                    <% if incomp != '' %>
                      <%= raw(incomp) %>
                    <% else %>
                      <p>学習中のレッスンはありません。</p>
                    <% end %>
                  </ul>
                </div>
                <div class="col-xs-12">
                  <h3 class="tangen">完了レッスン一覧</h3>
                  <ul>
                    <% if comp != '' %>
                      <%= raw(comp) %>
                    <% else %>
                      <p>完了レッスンはありません</p>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>

app/views/learnings/memo.html.erb
            <ul class="nav nav-tabs">
              <li><a href="<%= learnings_path %>">学習状況</a></li>
              <li class="active"><a><span style="font-size: 12px; line-height: 120%; !important">メモ・チェックレッスン</span></a></li>
              <li><a href="<%= friends_path %>">友達
                <% if @new_disp.present? && @new_disp == true %>
                  <span style="color: red; font-size: 12px">New</span>
                <% end %>
              </a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active" id="memo">
                <div class="col-xs-12">
                  <h3 class="tangen">学習メモ</h3>
                  <% if @memos.present? %>
                    <dl id="memo">
                      <% @memos.each do |m| %>
                        <% if m.memo.present? %>
                          <dt style="border-bottom: 1px solid #ccc; margin-bottom: 20px;">
                            <div class="row">
                              <div class="col-xs-8">・ 【中学<%= m.lesson.grade %>年生】<%= m.lesson.unit_name %>：<%= m.lesson.unit_item_name %>：<%= m.lesson.title %></div>
                              <div class="col-xs-3"><a href="/grade<%= m.lesson.grade %>/<%= m.lesson.unit_item_name %>/<%= m.lesson.id %>">Lessonを見る</a></div>
                              <div class="col-xs-1"><span class="caret"></span></div>
                            </div>
                          </dt>
                          <dd><%= m.memo %></dd>
                        <% end %>
                      <% end %>
                    </dl>
                  <% else %>
                    <p>学習メモはありません。</p>
                  <% end %>
                </div>
                <div class="col-xs-12">
                  <h3 class="tangen">チェックレッスン一覧</h3>
                  <% if @checks.present? %>
                    <% @checks.each do |c| %>
                      <ul>
                        <li style="border-bottom: 1px solid #ccc"><a href="/grade<%= c.lesson.grade %>/<%= c.lesson.unit_item_name %>/<%= c.lesson.id %>">【中学<%= c.lesson.grade %>年生】<%= c.lesson.unit_name %>：<%= c.lesson.unit_item_name %>：<%= c.lesson.title %></a></li>
                      </ul>
                    <% end %>
                  <% else %>
                    <p>チェックしたレッスンはありません。</p>
                  <% end %>
                </div>
              </div>
            </div>