config/routes.rb
Sko::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

  get "learnings/memo" => "learnings#memo"
  resources "learnings"

  resources "friends"

  resources "messages", :except => [:index, :show]

  get "faq/index"

  get 'contact/new' => 'contact#new', :as => 'contact'
  post 'contact/new' => 'contact#create'
  get 'contact:notice' => 'contact#index'

  get "lessons/new_lesson"
  get "lessons/ranking"
  get "lessons/category"
  get "lessons", :to => 'lessons#index', :as => 'lessons'

  get "grade3/index" => 'lessons#grade'
  get "grade2/index" => 'lessons#grade'
  get "grade1/index" => 'lessons#grade'
  match 'grade1/:type' => 'lessons#tangen', via: :get
  match 'grade1/:type/:lesson' => 'lessons#show', via: :get
  match 'grade2/:type' => 'lessons#tangen', via: :get
  match 'grade2/:type/:lesson' => 'lessons#show', via: :get
  match 'grade3/:type' => 'lessons#tangen', via: :get
  match 'grade3/:type/:lesson' => 'lessons#show', via: :get

  get 'agreement' => 'lessons#agreement'
  get 'privacy' => 'lessons#privacy'

  root :to => 'lessons#home'

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  # attr_accessible :status, :user_id1, :user_id2

  belongs_to :user1, :class_name => 'User' , :foreign_key => 'user_id1'
  belongs_to :user2, :class_name => 'User' , :foreign_key => 'user_id2'

  # belongs_to :from, :class_name => 'User' , :foreign_key => 'from'
  # belongs_to :to, :class_name => 'User' , :foreign_key => 'to'

  has_many :messages
end

app/controllers/friends_controller.rb
# coding utf-8

class FriendsController < ApplicationController

  add_breadcrumb 'Home', '/'

  protect_from_forgery

  before_filter :set_search
  before_filter :authenticate_user!

  def set_search
    @search = Lesson.search(params[:q])
  end

  def index

    add_breadcrumb '友達'

    @user_id = current_user.id

    @title = '友達'
    @description = '友達になっている、申請しているユーザ一覧ページです。また友達の検索も可能です。'


    # 友達
    # Friendテーブル（友達状況）から、友達のidを取ってくる
    @friend_ids = []
    @friend_ids += Friend.where(:user_id1 => @user_id, :status => true).pluck(:user_id2)
    @friend_ids += Friend.where(:user_id2 => @user_id, :status => true).pluck(:user_id1)
    # 上記idを元に、Userテーブルから情報を取ってくる
    @friends = User.where(:id => @friend_ids)

    # 友達申請
    # Friendテーブル（友達状況）から、友だち申請のあった人（status = false）のidを取ってくる
    @from_friend_ids = Friend.where(:to => @user_id, :status => false).pluck(:from)
    # 上記idを元にUserテーブルから情報を取ってくる
    @from_friends = User.where(:id => @from_friend_ids)

    # Newの表示
    @time_now = Time.now.to_i
    # Newの表示日
    dif_day = 3
    @new_period = 60 * 60 * 24 * dif_day

    @from_friend_times = Friend.where(:to => @user_id, :status => false).pluck(:updated_at)

    @new_disp = false
    @from_friend_times.each do |t|
      if @time_now - t.to_i < @new_period
        @new_disp = true
      end
    end

    @search_form = SearchForm.new params[:search_form]
    if params[:commit].present?
      @except_ids = []
      @user_ids2 = Friend.where(:status => true, :user_id1 => @user_id).pluck(:user_id2)
      @user_ids1 = Friend.where(:status => true, :user_id2 => @user_id).pluck(:user_id1)
      if @user_ids2.present?
        @except_ids.push(@user_ids2)
      end
      if @user_ids1.present?
        @except_ids.push(@user_ids1)
      end
      @except_ids.push(@user_id)
      @search_users = User.where.not(:id => @except_ids)
      @search_users = @search_users.named @search_form.q
      sex = Array
      if params[:search_form][:male] == '1' || params[:search_form][:female] == '1'
        if params[:search_form][:male] == '1'
          sex = '男性'
        end
        if params[:search_form][:female] == '1'
          sex = '女性'
        end
        if params[:search_form][:male] != '1' || params[:search_form][:female] != '1'
          @search_users = @search_users.where(:sex => sex)
        end
      end
      if params[:grade].present?
        @search_users = @search_users.where(:grade => params[:grade])
      end
    end
  end

  def show

    add_breadcrumb '友達', friends_path
    add_breadcrumb '友達詳細'

    @title = '友達の詳細ページ'
    @description = '友達の詳細ページになります。'

    @user_id = current_user.id
    @friend_id = params[:id].to_i

    @friend_info = User.where(:id => @friend_id)

    # プロフィール表示
    @chart_data_day = Learning.where("user_id = ? and status = ?", @friend_id, true).group('date(complete_date)').count
    @columun = 0
    @accumulation = 0
    @chart_data_accumulation = @chart_data_day.to_a
    @chart_data_day.each do |day|
      @chart_data_accumulation[@columun][0] = day[0]
      @chart_data_accumulation[@columun][1] = day[1] + @accumulation
      @accumulation = @chart_data_accumulation[@columun][1]
      @columun += 1
    end

    # Newの表示
    @time_now = Time.now.to_i
    # Newの表示日
    dif_day = 3
    @new_period = 60 * 60 * 24 * dif_day

    @from_friend_times = Friend.where(:to => @user_id, :status => false).pluck(:updated_at)

    @new_disp = false
    @from_friend_times.each do |t|
      if @time_now - t.to_i < @new_period
        @new_disp = true
      end
    end

    @sum_time = 0
    @friend_learning_ids = Learning.where("user_id = ? and status = ?", @friend_id, true).group('lesson_id').count('lesson_id').keys
    @times = Lesson.where(:id => @friend_learning_ids).select('time')
    @friend_complete_lessons = @friend_learning_ids.count

    if @times.present?
      @times.each do |t|
        @sum_time += t.time.min * 60 + t.time.sec
      end
    end

    @friend_total_time = Time.now.midnight.advance(:seconds => @sum_time).strftime('%T')

    # 友達状況
    if user_signed_in?
      if @user_id > @friend_id
        @friend = Friend.where("user_id1 = ? and user_id2 = ?", @friend_id, @user_id).first_or_create do |l|
          l.user_id1 = @friend_id
          l.user_id2 = @user_id
          l.status = nil
        end
      else
        @friend = Friend.where("user_id1 = ? and user_id2 = ?", @user_id, @friend_id).first_or_create do |l|
          l.user_id1 = @user_id
          l.user_id2 = @friend_id
          l.status = nil
        end
      end
    end

    # message機能
    @friend_messages = Message.find_all_by_friend_id(@friend.id)
    @message = Message.new

  end

  def create
      @friend = Friend.new(friend_params)
      if @friend.save
      redirect_to :back
    else
      render :template => "params[:controller]/params[:action]", :locals => {:friend => @friend}
    end
  end

  def update
    @friend = Friend.find(params[:id])
    if @friend.update(friend_params)
      redirect_to :back
    else
      render :template => "params[:controller]/params[:action]", :locals => {:friend => @friend}
    end
  end

  private

      def friend_params
          params[:friend].permit(:user_id1, :user_id2, :status, :from, :to)
      end

end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
            <ul class="nav nav-tabs">
              <li><a href="<%= learnings_path %>">学習状況</a></li>
              <li><a href="<%= learnings_memo_path %>"><span style="font-size: 12px; line-height: 120%; !important">メモ・チェックレッスン</a></li>
              <li class="active"><a>友達
                <% if @new_disp == true %>
                  <span style="color: red; font-size: 12px">New</span>
                <% end %>
              </a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active" id="friends">
                <div class="col-xs-12">
                  <h3>友達一覧</h3>
                <%= @friend_ids1 %>
                  <% if @friends.present? %>
                    <% @friends.each do |f| %>
                      <div class="col-md-2 col-xs-3">
                        <div class="user-img-wrapper">
                          <%= link_to image_tag(f.avatar.url(:thumb)), friend_path(f.id), :class => 'user-img' %>
                        </div>
                        <%= link_to f.name, friend_path(f.id) %>
                      </div>
                    <% end %>
                  <% else %>
                    <p>友達はいません。以下より友達を検索して、友達を作りましょう。</p>
                  <% end %>
                </div>
                <div class="col-xs-12">
                  <h3 class="tangen">友達申請</h3>
                  <% if @from_friends.present? %>
                    <% @from_friends.each do |f| %>
                      <div class="col-md-2 col-xs-3">
                        <div class="user-img-wrapper">
                          <%= link_to image_tag(f.avatar.url(:thumb)), friend_path(f.id), :class => 'user-img' %>
                        </div>
                        <% if f.created_at.to_i - @time_now < @new_period %>
                          <span style="color: red;">【New】</span>
                        <% end %>
                        <%= link_to f.name, friend_path(f.id) %>
                      </div>
                    <% end %>
                  <% else %>
                    <p>友達申請はありません。</p>
                  <% end %>
                </div>
                <div class="col-xs-12">
                  <h3 class="tangen">友達を探す</h3>
                  <%= @search_form.male %>
                  <%= form_for @search_form, url: friends_path, html: {method: :get, :class => 'form-horizontal'} do |f| %>
                    <div class="form-group">
                      <div class="col-xs-3">
                        <%= f.search_field :q, :class => 'form-control', :placeholder => '名前', :style => 'height: 20px;' %>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="col-xs-3">
                        <label>性別：</label>
                      </div>
                      <div class="col-xs-9">
                        <label><%= f.check_box :male %>男性</label>　
                        <label><%= f.check_box :female %>女性</label>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="col-xs-3">
                        <%= f.label :grade, '学年(学齢)：' %>
                      </div>
                      <div class="col-xs-9">
                        <label><input type="checkbox" name="grade[]" value="1" >小学生以下</label><br />
                        <label><input type="checkbox" name="grade[]" value="2" >中学1年生</label><br />
                        <label><input type="checkbox" name="grade[]" value="3" >中学2年生</label><br />
                        <label><input type="checkbox" name="grade[]" value="4" >中学3年生</label><br />
                        <label><input type="checkbox" name="grade[]" value="5" >高校1年生</label><br />
                        <label><input type="checkbox" name="grade[]" value="6" >高校2年生</label><br />
                        <label><input type="checkbox" name="grade[]" value="7" >高校3年生</label><br />
                        <label><input type="checkbox" name="grade[]" value="8" >それ以上</label><br />
                      </div>
                    </div>
                    <%= f.submit '検索する', :class => 'btn btn-default col-xs-offset-3', :style => 'width: 80px;' %>
                  <% end %>
                  <div id="search-result" class="row top15">
                  <% if params[:commit].present? %>
                    <% if @search_users.present? %>
                      <% @search_users.each do |s| %>
                        <div class="col-md-2 col-xs-3">
                          <div class="user-img-wrapper">
                            <%= link_to image_tag(s.avatar.url(:thumb)), friend_path(s.id), :class => 'user-img' %>
                          </div>
                          <%= link_to s.name, friend_path(s.id) %>
                        </div>
                      <% end %>
                    <% else %>
                      <p>一致するものがありませんでした。</p>
                    <% end %>
                  <% end %>
                  </div>
                </div>
              </div>
            </div>

app/views/friends/show.html.erb
            <ul class="nav nav-tabs">
              <li><a href="<%= learnings_path %>">学習状況</a></li>
              <li><a href="<%= learnings_memo_path %>"><span style="font-size: 12px; line-height: 120%; !important">メモ・チェックレッスン</a></li>
              <li class="active"><a>友達
                <% if @new_disp == true %>
                  <span style="color: red; font-size: 12px">New</span>
                <% end %>
              </a></li>
            </ul>
            <div class="row" style="margin-top: 15px;">
              <div class="col-xs-4 col-md-3" style="padding-left: 20px;">
                <div class="user-img-wrapper">
                  <%= image_tag @friend_info[0].avatar.url(:thumb), :class => 'user-img' %>
                </div>
                <div class="top10" style="clear: both;">
                  <% if @friend_info[0].comment.present? %>
                    <%= @friend_info[0].comment %>
                  <% end %>
                  <% if @friend.present? && @friend.status.nil? %>
                    <%= form_for @friend do |f| %>
                      <%= f.hidden_field :id, :value => @friend.id %>
                      <%= f.hidden_field :status, :value => 'false' %>
                      <%= f.hidden_field :from, :value => @user_id %>
                      <%= f.hidden_field :to, :value => @friend_id %>
                      <%= f.submit '友達になる', :class => "btn btn-default", :style => 'width: 100px;' %>
                    <% end %>
                  <% elsif @friend.present? && @friend.status == false && @friend.to == @user_id %>
                    <%= form_for @friend do |f| %>
                      <%= f.hidden_field :id, :value => @friend.id %>
                      <%= f.hidden_field :status, :value => 'true' %>
                      <%= f.submit '友達になる', :class => "btn btn-default", :style => 'width: 100px;' %>
                    <% end %>
                  <% elsif @friend.present? && @friend.status == false && @friend.from == @user_id %>
                    <button type="button" class="btn btn-default" disabled="disabled">友達申請中</button>
                  <% end %>
                </div>
              </div>
              <div class="col-xs-8 col-md-3">
                <p><%= @friend_info[0].name %></p>
                <p><%= @friend_info[0].prefecture %></p>
                <p>
                  <% if @friend_info[0].grade == 1 %>
                    <%= '小学生以下' %>
                  <% elsif @friend_info[0].grade == 2 %>
                    <%= '中学1年生' %>
                  <% elsif @friend_info[0].grade == 3 %>
                    <%= '中学2年生' %>
                  <% elsif @friend_info[0].grade == 4 %>
                    <%= '中学3年生' %>
                  <% elsif @friend_info[0].grade == 5 %>
                    <%= '高校1年生' %>
                  <% elsif @friend_info[0].grade == 6 %>
                    <%= '高校2年生' %>
                  <% elsif @friend_info[0].grade == 7 %>
                    <%= '高校3年生' %>
                  <% else %>
                    <%= '大学生以上' %>
                  <% end %>
                </p>
              </div>
              <div class="col-xs-8 col-md-6">
                <p>完了レッスン数：　<%= @friend_complete_lessons %></p>
                <p>総学習時間：　<%= @friend_total_time %></p>
                <p><%= link_to '友達一覧に戻る　>>', friends_path %></p>
              </div>
            </div>
            <% if @friend.present? && @friend.status == true %>
                <div class="clearfix">
                  <div class="col-xs-12" style="border: 1px solid #ccc; margin-top: 7px; padding-top: 7px; padding-bottom: 7px;">
                    <% if @friend_messages.present? %>
                      <% @friend_messages.each do |m| %>
                        <% if m.user_id == @user_id %>
                          <div class="row">
                            <div class="col-xs-6 col-xs-offset-3 col-md-8 col-md-offset-2">
                              <p class="message text-right"><%= raw(hbr(m.message_content)) %></p>
                            </div>
                            <div class="col-xs-3 col-md-2">
                              <div class="user-img-wrapper">
                                <%= image_tag m.user.avatar.url(:thumb) %>
                              </div>
                            </div>
                          </div>
                        <% else %>
                          <div class="row">
                            <div class="col-xs-3 col-md-2">
                              <div class="user-img-wrapper">
                                <%= image_tag m.user.avatar.url(:thumb) %>
                              </div>
                            </div>
                            <div class="col-xs-6 col-md-8">
                              <p style="border: 1px solid #ccc; margin-right: 10px; margin-top: 10px;"><%= raw(hbr(m.message_content)) %></p>
                            </div>
                          </div>
                        <% end %>
                      <% end %>
                    <% end %>
                    <%= form_for @message do |f| %>
                      <fieldset>
                        <div class="form-group">
                          <%= f.hidden_field :friend_id, :value => @friend.id %>
                          <%= f.hidden_field :user_id, :value => @user_id %>
                          <label for="exampleInput">友達へのメッセージを記入してください。</label>
                          <%= f.text_area :message_content, :class =>  "form-control", :placeholder => "メッセージ", :style => "height: 120px;" %>
                        </div>
                        <%= f.submit 'メッセージを送る', :class => "btn btn-default" %>
                      </fieldset>
                    <% end %>
                  </div>
                </div>
              <% end %>
              <% if @chart_data_day.count > 0 %>
                <div style="border: 1px solid #ccc; margin-top: 7px;">
                  <div class="tab-content">
                    <div class="tab-pane active" id="days">
                      <h3>日別学習レッスン数</h3>
                      <%= line_chart @chart_data_day, height: "300px" %>
                    </div>
                    <div class="tab-pane" id="total">
                      <h3>累積学習レッスン数</h3>
                      <%= line_chart @chart_data_accumulation, height: "300px" %>
                    </div>
                  </div>
                  <ul class="nav nav-pills nav-justified">
                    <li class="active"><a href="#days" data-toggle="tab">日別学習時間</a></li>
                    <li><a href="#total" data-toggle="tab">累積学習時間</a></li>
                  </ul>
                </div>
              <% end %>