config/routes.rb
Sko::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

  get "learnings/memo" => "learnings#memo"
  resources "learnings"

  resources "friends"

  resources "messages", :except => [:index, :show]

  get "faq/index"

  get 'contact/new' => 'contact#new', :as => 'contact'
  post 'contact/new' => 'contact#create'
  get 'contact:notice' => 'contact#index'

  get "lessons/new_lesson"
  get "lessons/ranking"
  get "lessons/category"
  get "lessons", :to => 'lessons#index', :as => 'lessons'

  get "grade3/index" => 'lessons#grade'
  get "grade2/index" => 'lessons#grade'
  get "grade1/index" => 'lessons#grade'
  match 'grade1/:type' => 'lessons#tangen', via: :get
  match 'grade1/:type/:lesson' => 'lessons#show', via: :get
  match 'grade2/:type' => 'lessons#tangen', via: :get
  match 'grade2/:type/:lesson' => 'lessons#show', via: :get
  match 'grade3/:type' => 'lessons#tangen', via: :get
  match 'grade3/:type/:lesson' => 'lessons#show', via: :get

  get 'agreement' => 'lessons#agreement'
  get 'privacy' => 'lessons#privacy'

  root :to => 'lessons#home'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/agreement.rb
class Agreement < ActiveRecord::Base
  # attr_accessible :content
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, :email, :inquiry, :content, presence: true
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  belongs_to :faq_category
  # attr_accessible :answer, :question, :faq_category_id
end

app/models/faq_category.rb
class FaqCategory < ActiveRecord::Base
  # attr_accessible :faq_category_name, :faq_category_summary
  has_many :faq
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  # attr_accessible :status, :user_id1, :user_id2

  belongs_to :user1, :class_name => 'User' , :foreign_key => 'user_id1'
  belongs_to :user2, :class_name => 'User' , :foreign_key => 'user_id2'

  # belongs_to :from, :class_name => 'User' , :foreign_key => 'from'
  # belongs_to :to, :class_name => 'User' , :foreign_key => 'to'

  has_many :messages
end

app/models/learning.rb
class Learning < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson, :order => 'grade'
  # attr_accessible :check, :complete_date, :memo, :status
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  # attr_accessible :title, :summary, :movie, :time, :grade, :category_name, :category_summary, :unit_name, :unit_summary, :unit_item_name, :unit_item_summary, :explanation, :exercise, :exercise_answer, :point, :number
  has_many :learnings

  has_attached_file :exe_pdf
  validates_attachment_content_type :exe_pdf, :content_type => ["application/pdf"]

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :friend
  belongs_to :user

  # attr_accessible :message_content

end

app/models/privacy.rb
class Privacy < ActiveRecord::Base
  # attr_accessible :content
end

app/models/search_form.rb
# coding : utf-8

class SearchForm
  # extend ActiveModel::Naming
  # include ActiveModel::Conversion
  include ActiveModel::Model

  attr_accessor :q, :male, :female, :grade

  def initialize(params)
    self.q = params[:q] if params
  end

  def persisted?
    false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :avatar, :user_auth, :sex, :grade, :prefecture, :mailmag

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "70x70" }
  validates_attachment_size :avatar, :less_than => 1.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']

  has_many :friends
  has_many :learnings
  has_many :messages

  # validates :name, :avatar, :sex, :grade, :prefecture, presence: true

  scope :named, ->(q) { where 'name like ?', "%#{q}%" }

  # allow users to update their accounts without passwords
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

end

app/controllers/faq_controller.rb
# coding utf-8

class FaqController < ApplicationController

  add_breadcrumb 'Home', '/'

  before_filter :set_search

  def set_search
  @search = Lesson.search(params[:q])
  end

  def index

    add_breadcrumb 'よくある質問'

    @title = 'よくある質問'
    @description = '当サイトによせられる、よくある質問一覧です。'

    @faqs = Faq.all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  # HTMLで書けない文字の実体参照と改行コードのHTMLへの置換を行う
  def hbr(target)
  target = html_escape(target)
  target.gsub(/\r\n|\r|\n/, "<br />")
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/learnings_helper.rb
module LearningsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
  <meta name="description" content="<%= @description ? @description : "中学数学の問題を解けるようになるサイトです。絵を書いて問題を解き、理解できるように解説します。" %>">
  <meta name="author" content="SKO">
  <link rel="shortcut icon" href="img/favicon.ico">
  <title><%= @title ? @title + " | 中学数学を解けるようになるサイト" : "中学数学が解けるようになるサイト サイト名" %></title>

  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>

  <!-- google charts -->
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>

  <!-- glyphicon Bootstrapサイトのアイコンのリンク先 -->
  <link href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">

  <script>
    $(function() {
      $(window).hashchange(function(){
        var pos = $("a[name='" + location.hash.substr(1) + "']").offset().top;
        // $('html, body').animate({ scrollTop: pos - 40 }, 0); // does not jump well on page load on safari
        // $('html, body').animate({ scrollTop: pos - 40 }, 1); // works, but have to wait 1ms
        window.scrollTo(0, pos - 40); // worked on safari, chrome, firefox well
      });
      // trigger the event on page load.
      if (location.hash) { $(window).hashchange(); }
    });
  </script>
</head>
<body onload="load()">

<!--Nav-->
<%= render 'shared/globalNav' %>
<!--//Nav-->

<!-- パンくず -->
<% if params[:controller] != 'lessons' || params[:action] != 'home' %>
  <%= render 'shared/bread' %>
<% end %>
<!-- //パンくず -->

<!--mainVisual-->
<% if params[:controller] == 'lessons' && params[:action] == 'home' %>
  <%= render 'shared/mainVisual' %>
<% end %>
<!--//mainVisual-->

<!--Contents-->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">

      <!-- Main -->
      <div class="col-sm-8 col-sm-push-4 cont-main">
        <div class="content">
          <div class="clearfix">
<%= yield %>
          </div>
        </div><!-- //content -->
      </div>
      <!-- //Main -->

      <!-- Sidebar -->
      <div class="col-sm-4 col-sm-pull-8 cont-sidebar">
<%= render 'shared/sidebar' %>
      </div>
      <!-- //Sidebar -->

    </div><!-- //row -->
  </div><!-- //container -->
</div><!-- //Contents-->

<!-- footer -->
<footer class="cont-footer">
  <div class="container">
    <div class="row">
<%= render 'shared/footer' %>
    </div>
  </div>
  <div class="container">
    <span class="copyright">
      &copy; Copyright <a href="/">ビジュアル数学</a> All Rights Reserved.
    </span>
  </div>
</footer><!-- //footer -->

<!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery.js"></script>
<%= javascript_include_tag "bootstrap.min" %>
<script>
  $(function() {
    $("[data-toggle=tooltip]").tooltip({
      placement: 'bottom'
    });
    $("[data-toggle=popover]").popover();
  });

  $(function() {
    setTimeout(function() {
      $('#notice').fadeOut("slow");
    }, 800);

  });

  $(function(){
    $("#faq dt, #memo dt").on("click", function() {
      $(this).next().slideToggle("fast");
      $(this).toggleClass("active");
    });
  });
</script>

</body>
</html>

app/views/shared/_bread.html.erb
  <div id="bread">
    <div class="container"><%= render_breadcrumbs %></div>
  </div>

app/views/shared/_footer.html.erb
      <div class="col-xs-12 col-md-4">
        <div class="clearfix">
          <h3><%= link_to '中学1年生', grade1_index_path %></a></h3>
          <% if @footer_grade1.present? %>
            <ul>
              <% @footer_grade1.each do |unit| %>
                <li><%= link_to unit.unit_name, '/grade1/index#' + unit.unit_name %></li>
              <% end %>
            </ul>
          <% else %>
            <p>準備中です</p>
          <% end %>
          <h3><%= link_to '中学2年生', grade2_index_path %></h3>
          <% if @footer_grade2.present? %>
            <ul>
              <% @footer_grade2.each do |unit| %>
                <li><%= link_to unit.unit_name, '/grade2/index#' + unit.unit_name %></li>
              <% end %>
            </ul>
          <% else %>
            <p>準備中です</p>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-md-4">
        <div class="clearfix">
          <h3><%= link_to '中学3年生', grade3_index_path %></h3>
          <% if @footer_grade3.present? %>
            <ul>
              <% @footer_grade3.each do |unit| %>
                <li><%= link_to unit.unit_name, '/grade3/index#' + unit.unit_name %></a></li>
              <% end %>
            </ul>
          <% else %>
            <p>準備中です</p>
          <% end %>
          <h3><%= link_to 'カテゴリ', lessons_category_path %></h3>
          <% if @footer_categories.present? %>
            <ul>
              <% @footer_categories.each do |category| %>
                <li><%= link_to category.category_name, lessons_category_path + '#' + category.category_name %></a></li>
              <% end %>
            </ul>
          <% else %>
            <p>準備中です</p>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-md-4">
        <div class="clearfix">
          <h3>ご利用にあたって</h3>
          <ul class="footer-list">
            <li><a href="/cat_list/1">このサイトの使い方</a></li>
            <li><%= link_to 'お問合せ', contact_path %></li>
            <li><a href="/about/sitemap" title="サイトマップ">サイトマップ</a></li>
            <li><%= link_to '利用規約', agreement_path %></li>
            <li><%= link_to 'プライバシーポリシー', privacy_path %></li>
            <li><a href="/cat_list/1">サイト運営者</a></li>
          </ul>
        </div>
      </div>
      <p class="text-right">
        <a href="#">Back to top</a>
      </p>

app/views/shared/_globalNav.html.erb
<div class="global">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a id="logo" class="navbar-brand" href="/"><span class="blue">ビジュアル数学</span></a>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li<% if params[:controller] == 'learnings' && params[:action] == 'index' %><%= ' class=active' %><% end %>><%= link_to 'マイページ', learnings_path, :style => "color:orange;" %></a></li>
        <% end %>
        <li<% if request.path_info[6,1] == '1' %><%= ' class=active' %><% end %>><%= link_to '中学1年生', grade1_index_path %></li>
        <li<% if request.path_info[6,1] == '2' %><%= ' class=active' %><% end %>><%= link_to '中学2年生', grade2_index_path %></li>
        <li<% if request.path_info[6,1] == '3' %><%= ' class=active' %><% end %>><%= link_to '中学3年生', grade3_index_path %></li>
      </ul>
      <div class="form-group navbar-form navbar-left hidden-xs hidden-sm">
        <%= search_form_for @search, url: lessons_path do |f| %>
          <%= f.text_field :summary_or_title_or_grade_or_category_name_or_category_summary_or_unit_name_or_unit_summary_or_unit_item_name_or_unit_item_summary_cont, :placeholder => "レッスン検索", :size => "13px", :class => "form-control" %>
          <%= f.submit '検索', :class => "btn btn-default" %>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li<% if params[:controller] == 'contact' && params[:action] == 'new' %><%= ' class=active' %><% end %>><%= link_to 'お問合せ', contact_path %></li>
        <li>
          <% if user_signed_in? %>
            <%= link_to "ログアウト", destroy_user_session_path, :method => :delete %>
          <% else %>
            <%= link_to "ログイン", new_user_session_path %>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</div>

app/views/shared/_grade_index.html.erb
                <div class="row">
                  <div class="col-xs-12">
                    <h2><%= @grade %></h2>
                    <%= image_tag '740x320.png', :alt => 'Main_Visual', :class => 'img-responsive bottom20'%>
                  </div>
                  <div class="col-md-6">
                    <% if @grade_units.present? %>
                      <% @grade_units.each do |unit| %>
                        <h3 id="<%= unit.unit_name %>"><%= unit.unit_name %></h3>
                        <ul>
                        <% @grade_units_all.each do |item| %>
                          <% if item.unit_name == unit.unit_name %>
                            <li><%= link_to item.unit_item_name, item.unit_item_name %></li>
                          <% end %>
                        <% end %>
                        </ul>
                      <% end %>
                    <% else %>
                      <ul>
                        <li>準備中です</li>
                      </ul>
                    <% end %>
                  </div>
                  <div class="col-md-6">
                    <h3>関数</h3>
                    <ul>
                      <li>関数</li>
                      <li>比例</li>
                      <li>反比例</li>
                      <li>座標</li>
                      <li>比例グラフ</li>
                      <li>反比例グラフ</li>
                    </ul>
                    <h3>図形</h3>
                    <ul>
                      <li>図形（用語と記号）</li>
                      <li>図形の移動</li>
                      <li>作図</li>
                      <li>円とおうぎ形</li>
                      <li>おうぎ形の弧、面積</li>
                    </ul>
                    <h3>資料</h3>
                    <ul>
                      <li>近似値</li>
                    </ul>
                  </div>
                </div>

app/views/shared/_mainVisual.html.erb
<div id="mainvisual">
  <div class="mainVisual_wrapper section">
    <div class="container">
      <div class="row mainVisual_bg">
        <div class="col-md-8">
          <%= image_tag 'mainVisual.jpg', :alt => 'Main_Visual', :class => 'img-responsive' %>
        </div>
        <div class="col-md-4">
          <div class="hidden-xs hidden-sm">
            <% if user_signed_in? %>
              <ul class="profile">
                <li><div class="user-img-wrapper"><%= image_tag @user_info[0].avatar.url(:thumb), :class => "user-img" %></div>　<%= @user_info[0].name %></li>
                <li>【総学習時間】　　<%= @user_total_time %></li>
                <li>【完了レッスン数] 　<%= @user_learning_ids.count %>レッスン</li>
                <% if @user_info[0].comment.present? %>
                <li><p class="bg-success" style="padding: 10px;"><%= @user_info[0].comment %></p></li>
                <% end %>
                <li class="text-right"><%= link_to 'プロフィール確認・編集', edit_user_registration_path(@user_id) %></li>
              </ul>
            <% else %>
              <%= form_for(:user, :url => session_path(:user), :html => { :class => 'form-horizontal' }) do |f| %>
                <div class="form-group">
                  <div class="col-md-10 col-md-offset-1">
                    <%= f.text_field :email, :class => 'form-control', :placeholder => 'メールアドレス' %>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-10 col-md-offset-1">
                    <%= f.password_field :password, :class => 'form-control', :placeholder => 'パスワード' %>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-10 col-md-offset-1">
                    <%= f.check_box :remember_me%>
                    <%= f.label :remember_me, 'ログイン情報を記憶する'  %>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-10 col-md-offset-1">
                    <%= f.submit 'ログイン', :class => 'btn btn-default' %>
                  </div>
                </div>
              <% end %>
              <hr class="col-md-10 col-md-offset-1">
              <div class="form-group">
                <div class="col-md-6">
                  <button type="button" class="btn btn-default form-left" onclick="location.href='/users/sign_up'" style="width:140px;">新規ユーザ登録</button>
                </div>
                <div class="col-md-6">
                  <button type="button" class="btn btn-default"onclick="location.href='/users/password/new'" style="width:140px;">パスワード再発行</button>
                </div>
              </div>
  <!--             <div class="form-group">
                <div class="col-md-6">
                  <button type="button" class="btn btn-default form-left" onclick="location.href='/'" style="width:140px;">Facebookログイン</button>
                </div>
                <div class="col-md-6">
                  <button type="button" class="btn btn-default"onclick="location.href='/'" style="width:140px;">Twitterログイン</button>
                </div>
              </div> -->
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
        <% if user_signed_in? && (params[:controller] != 'lessons' || params[:action] != 'home') %>
          <div class="sidebar">
            <h4>プロフィール</h4>
            <ul class="profile">
              <li><div class="user-img-wrapper"><%= image_tag @user_info[0].avatar.url(:thumb), :class => "user-img" %></div>　<%= @user_info[0].name %></li>
              <li class="top10" style="clear: both;">【総学習時間】　　<%= @user_total_time %>　(<%= @user_rank %>位)</li>
              <li>【完了レッスン数] 　<%= @user_learning_ids.count %>レッスン</li>
              <% if @user_info[0].comment.present? %>
              <li><p class="bg-success" style="padding: 10px;"><%= @user_info[0].comment %></p></li>
              <% end %>
              <li class="text-right"><%= link_to 'プロフィール確認・編集', edit_user_registration_path(@user_id) %></li>
            </ul>
          </div>
        <% end %>

        <div class="sidebar">
          <h4>新着レッスン</h4>
          <ul>
            <% if @new_lessons.present? %>
              <% @new_lessons.each do |lesson| %>
                <li class="sidebar-indent"><%= lesson.created_at.strftime('%y.%m.%d') %> <%= link_to '【中学'+lesson.grade.to_s+'年生】'+lesson.unit_name+'：'+lesson.unit_item_name , '/grade'+lesson.grade.to_s+'/'+lesson.unit_item_name %></li>
              <% end %>
            <% else %>
              <li>準備中です</li>
            <% end %>
              <li class="text-right"><a href="/lessons/new_lesson">新着レッスン一覧</a></li>
          </ul>
        </div>

        <div class="sidebar">
          <h4>人気レッスン</h4>
          <ul>
            <% if @popular_lessons.present? %>
              <% @count = 0 %>
              <% @popular_lessons.each do |lesson| %>
                <% if @count < 5 %>
                  <li class="sidebar-indent"><%= link_to '【中学'+lesson.grade.to_s+'年生】'+lesson.unit_name+'：'+lesson.unit_item_name , '/grade'+lesson.grade.to_s+'/'+lesson.unit_item_name %></li>
                  <% @count += 1 %>
                <% end %>
              <% end %>
            <% else %>
              <li>準備中です</li>
            <% end %>
            <li class="text-right"><%= link_to '人気レッスン一覧', lessons_ranking_path %></li>
          </ul>
        </div>

        <div class="sidebar">
          <h4>ユーザ情報</h4>
          <ul>
            <li class="sidebar-indent">登録者数：<%= @users_total %>人</li>
            <% if @users_grade.present? %>
              <% @count = 0 %>
                <% @users_grade.each do |choice, num| %>
                  <% if choice == 2 || choice == 3 || choice == 4 %>
                    <li class="sidebar-indent">　中学<%= choice - 1 %>年生；<%= num %>人</li>
                  <% else %>
                    <% @count += num %>
                  <% end %>
                <% end %>
              <li class="sidebar-indent">　それ以外：<%= @count %>人</li>
            <% end %>

            <li class="sidebar-indent">平均完了レッスン：<%= @average_comp %>レッスン</li>
            <li class="sidebar-indent">平均チェックレッスン：<%= @average_check %>レッスン</li>
          </ul>
        </div>

        <div class="sidebar">
          <h4>ソーシャル</h4>
          <ul>
            <li>
              <a href="https://twitter.com/twitteraccount" class="twitter-follow-button" data-show-count="false" data-lang="ja">@twitteraccountさんをフォロー</a>
              <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
            </li>
            <li>
              <div class="fb-like" data-href="https://www.facebook.com/FBaccount" data-width="240" data-layout="button" data-action="like" data-show-faces="true" data-share="true"></div>
            </li>
          </ul>
        </div>

app/views/shared/_tangen.html.erb
          <div class="row">
            <div class="col-xs-12">
              <h2><%= @grade_unit_item_name %></h2>
              <%= image_tag '740x320.png', :alt => 'Main_Visual', :class => 'img-responsive'%>
            </div>
            <div class="col-xs-12">
              <h3 class="tangen">レッスン一覧</h3>
              <% if @grade_lessons.present? %>
                <% @grade_lessons.each do |lesson| %>
                  <h4 class="tangen"><%= link_to lesson.title, @grade_unit_item_name+'/'+lesson.id.to_s %></h4>
                  <p><%= lesson.summary %></p>
                  <p><%= link_to raw(lesson.exercise)+'('+lesson.title+')', @grade_unit_item_name+'/'+lesson.id.to_s %></p>
                <% end %>
              <% else %>
                <p>準備中です</p>
              <% end %>
              <% if @grade_lessons.present? %>
                <% @grade_lessons.each do |lesson| %>
                <% end %>
              <% else %>
                <p>準備中です</p>
              <% end %>
            </div>
          </div>