config/routes.rb
Sko::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {
    :sessions      => "users/sessions",
    :registrations => "users/registrations",
    :passwords     => "users/passwords"
  }

  get "learnings/memo" => "learnings#memo"
  resources "learnings"

  resources "friends"

  resources "messages", :except => [:index, :show]

  get "faq/index"

  get 'contact/new' => 'contact#new', :as => 'contact'
  post 'contact/new' => 'contact#create'
  get 'contact:notice' => 'contact#index'

  get "lessons/new_lesson"
  get "lessons/ranking"
  get "lessons/category"
  get "lessons", :to => 'lessons#index', :as => 'lessons'

  get "grade3/index" => 'lessons#grade'
  get "grade2/index" => 'lessons#grade'
  get "grade1/index" => 'lessons#grade'
  match 'grade1/:type' => 'lessons#tangen', via: :get
  match 'grade1/:type/:lesson' => 'lessons#show', via: :get
  match 'grade2/:type' => 'lessons#tangen', via: :get
  match 'grade2/:type/:lesson' => 'lessons#show', via: :get
  match 'grade3/:type' => 'lessons#tangen', via: :get
  match 'grade3/:type/:lesson' => 'lessons#show', via: :get

  get 'agreement' => 'lessons#agreement'
  get 'privacy' => 'lessons#privacy'

  root :to => 'lessons#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, :email, :inquiry, :content, presence: true
end

app/controllers/contact_controller.rb
# coding: utf-8

class ContactController < ApplicationController

  add_breadcrumb 'Home', '/'

  before_filter :authenticate_user!, :except => [:index, :new, :create]

  protect_from_forgery

  before_filter :set_search

  def set_search
  @search = Lesson.search(params[:q])
  end

  def index
    add_breadcrumb 'お問合せ完了'

    @notice = params[:notice]

    @title = 'お問合せ完了'
    @description = 'お問合せが完了しました。'
  end

  def new
    add_breadcrumb 'お問合せ'

    @contact = Contact.new

    @title = 'お問合せ'
    @description = '当サイトへのお問合せ送信ページとなります。'
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.sent(@contact).deliver
      redirect_to :action => :index, :notice => 'お問い合わせありがとうございました。'
    else
      render :action => :new, :alert => 'お問い合わせに不備があります。'
    end
  end

  def contact_params
    params.require(:contact).permit(:name, :email, :inquiry, :content)
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/index.html.erb
<h1>お問い合わせ完了</h1>
<p>お問合わせが完了しました。</p>
<p>お問合わせに関するご連絡は3〜5営業日にご連絡いたします。</p>
<p>※お問合わせ内容によって、ご回答できない場合がございますので、予めご了承ください。</p>

app/views/contact/new.html.erb
    <h2>お問合わせ</h2>
    <p>本サイト、レッスン内容などに関するご質問、その他、サービスに関するお問合わせフォームとなります。</p>
    <div class="alert alert-info">
      <p>お問合せの前に「よくある質問」をご覧ください。</p>
      <%= link_to '「よくある質問」はこちら', faq_index_path %>
    </div>
    <h2>お問合せフォーム</h2>
    <% if @contact.errors.any? %>
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_for @contact, :url => contact_path, :html => { :class => 'form-horizontal' } do |f| %>
      <div class="form-group">
        <div class="col-sm-6">
          <%= f.text_field :name, :autofocus => true, :class => 'form-control', :placeholder => 'お名前'  %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-6">
          <%= f.email_field :email, :autofocus => true, :class => 'form-control', :placeholder => 'メールアドレス' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-xs-3">
          <%= f.label :inquiry, 'お問合わせ内容：' %>
        </div>
        <div class="col-xs-9">
          <label><%= f.radio_button :inquiry, '1', { :checked => true } %>レッスン内容について</label><br>
          <label><%= f.radio_button :inquiry, '2' %>サイト運営について</label><br>
          <label><%= f.radio_button :inquiry, '3' %>その他</label>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-6">
          <%= f.text_area :content, :autofocus => true, :class => 'form-control', :placeholder => '具体的な内容' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-xs-9 col-xs-offset-3">
          <dd><%= f.submit "メール送信", :class => 'btn btn-default' %></dd>
        </div>
      </div>
    <% end %>